import { Destination, GuideProfile, Booking, Review } from '../types';

export const INITIAL_DESTINATIONS: Destination[] = [
  {
    id: 'dest-1',
    slug: 'sigiriya-rock-fortress',
    name: 'Sigiriya Rock Fortress',
    location: 'Matale District, Central Province',
    category: 'Heritage',
    description: 'An ancient palace complex perched atop a 200-meter granite rock, featuring ancient frescoes and water gardens.',
    mainImage: 'https://images.unsplash.com/photo-1586227740560-8cf2732c1531?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1586227740560-8cf2732c1531?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80'
    ],
    rating: 4.9,
    bestSeason: 'November to April',
    duration: 'Half Day (3-4 hours)',
    entranceFeeUSD: 36,
    openingHours: '06:30 AM - 05:30 PM',
    activities: ['Rock Climbing', 'Photography', 'Archaeological Tour', 'Museum Visit'],
    nearbyAttractions: ['Pidurangala Rock', 'Dambulla Cave Temple', 'Minneriya Safari'],
    isHiddenGem: false,
    tags: ['UNESCO', 'History', 'Iconic', 'Panoramas']
  },
  {
    id: 'dest-2',
    slug: 'ella-nine-arch-bridge',
    name: 'Ella & Nine Arch Bridge',
    location: 'Badulla District, Uva Province',
    category: 'Hill Country',
    description: 'A picturesque mountain village surrounded by tea plantations, waterfalls, and the world-famous colonial railway bridge.',
    mainImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80'
    ],
    rating: 4.8,
    bestSeason: 'January to May',
    duration: '2-3 Days',
    entranceFeeUSD: 0,
    openingHours: 'Open 24 Hours',
    activities: ['Train Ride', 'Hiking Little Adam’s Peak', 'Zip-lining', 'Tea Factory Visit'],
    nearbyAttractions: ['Ravana Falls', 'Ella Rock', 'Diyaluma Falls'],
    isHiddenGem: false,
    tags: ['Nature', 'Hiking', 'Scenic Train', 'Tea']
  },
  {
    id: 'dest-3',
    slug: 'galle-dutch-fort',
    name: 'Galle Dutch Fort',
    location: 'Galle, Southern Province',
    category: 'Heritage',
    description: 'A 17th-century coastal fortress blending European architecture and South Asian traditions, lined with artisan shops and cafes.',
    mainImage: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80'],
    rating: 4.7,
    bestSeason: 'December to April',
    duration: '1 Day',
    entranceFeeUSD: 0,
    openingHours: 'Open 24 Hours',
    activities: ['Sunset Walk', 'Boutique Shopping', 'Lighthouse Visit', 'Culinary Tours'],
    nearbyAttractions: ['Unawatuna Beach', 'Jungle Beach', 'Koggala Lake'],
    isHiddenGem: false,
    tags: ['UNESCO', 'Coastal', 'Architecture', 'Shopping']
  },
  {
    id: 'dest-4',
    slug: 'yala-national-park',
    name: 'Yala National Park',
    location: 'Hambantota, Southern Province',
    category: 'Wildlife',
    description: 'Sri Lanka’s most visited wildlife sanctuary, renowned for possessing one of the highest leopard densities in the world.',
    mainImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    gallery: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80'],
    rating: 4.8,
    bestSeason: 'February to July',
    duration: '1 Full Day',
    entranceFeeUSD: 40,
    openingHours: '06:00 AM - 06:00 PM',
    activities: ['4x4 Jeep Safari', 'Leopard Tracking', 'Bird Watching', 'Camping'],
    nearbyAttractions: ['Kataragama Sacred City', 'Bundala National Park'],
    isHiddenGem: false,
    tags: ['Leopards', 'Safari', 'Wild Elephants', 'Adventure']
  }
];

export const INITIAL_GUIDES: GuideProfile[] = [
  {
    id: 'guide-1',
    userId: 'u-guide-1',
    fullName: 'Kusal Perera',
    email: 'kusal.guide@ceylonguide.lk',
    phone: '+94 77 123 4567',
    bio: 'SLTDA Licensed National Tour Guide with 8+ years experience specializing in Cultural Heritage and Wildlife Safaris across Sri Lanka.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    languages: ['English', 'German', 'Sinhala'],
    specializations: ['Heritage & History', 'Wildlife Safaris', 'Photography'],
    experienceYears: 8,
    dailyRateUSD: 65,
    rating: 4.9,
    reviewCount: 42,
    isVerified: true,
    status: 'APPROVED',
    location: 'Kandy / Central Province',
    licenseNumber: 'SLTDA/NTG/2018/0891',
    availabilityDates: ['2026-08-20', '2026-08-21', '2026-08-22', '2026-08-25'],
  },
  {
    id: 'guide-2',
    userId: 'u-guide-2',
    fullName: 'Chaminda Silva',
    email: 'chaminda@ceylonguide.lk',
    phone: '+94 71 987 6543',
    bio: 'Southern coast specialist with expert knowledge in surfing spots, secret waterfalls, and culinary street food tours in Galle and Mirissa.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    languages: ['English', 'French', 'Sinhala'],
    specializations: ['Beach & Water Sports', 'Culinary Tours', 'Eco Trekking'],
    experienceYears: 6,
    dailyRateUSD: 55,
    rating: 4.8,
    reviewCount: 29,
    isVerified: true,
    status: 'APPROVED',
    location: 'Galle / Southern Province',
    licenseNumber: 'SLTDA/NTG/2020/1102',
    availabilityDates: ['2026-08-18', '2026-08-19', '2026-08-20', '2026-08-21'],
  }
];